/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.aea;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Morales
 */
public class GastosPagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GastosPagos
     */
    public GastosPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCALCULAR = new javax.swing.JButton();
        btnNUEVO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSALIR = new javax.swing.JButton();
        cbMESES = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFECHA = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chkLUZ = new javax.swing.JCheckBox();
        chkAGUA = new javax.swing.JCheckBox();
        chkLOCAL = new javax.swing.JCheckBox();
        txtLUZ = new javax.swing.JTextField();
        txtAGUA = new javax.swing.JTextField();
        txtLOCAL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblHORA = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chkDOCENTE = new javax.swing.JCheckBox();
        txtDOCENTE = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cbESTADO = new javax.swing.JComboBox<>();
        txtBONO = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        chkAFP = new javax.swing.JCheckBox();
        chkESSALUD = new javax.swing.JCheckBox();
        txtAFP = new javax.swing.JTextField();
        txtESSALUD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPagoDocente = new javax.swing.JTextField();
        btnResolver = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnCALCULAR.setText("Calcular");
        btnCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCALCULARActionPerformed(evt);
            }
        });

        btnNUEVO.setText("Nuevo");
        btnNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNUEVOActionPerformed(evt);
            }
        });

        jLabel4.setText("Mes:");

        btnSALIR.setText("SALIR");
        btnSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSALIRActionPerformed(evt);
            }
        });

        cbMESES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setText("Total a pagar por mes:");

        jLabel2.setText("Fecha:");

        txtTOTAL.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Registro de Gastos Basicos");

        lblFECHA.setText("jLabel3");

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("GASTOS"));

        chkLUZ.setText("Luz");
        chkLUZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLUZActionPerformed(evt);
            }
        });

        chkAGUA.setText("Agua");
        chkAGUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAGUAActionPerformed(evt);
            }
        });

        chkLOCAL.setText("Local");
        chkLOCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLOCALActionPerformed(evt);
            }
        });

        txtLUZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLUZActionPerformed(evt);
            }
        });

        txtLOCAL.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(chkLUZ)
                .addGap(37, 37, 37)
                .addComponent(txtLUZ, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(chkAGUA)
                .addGap(18, 18, 18)
                .addComponent(txtAGUA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(chkLOCAL)
                .addGap(18, 18, 18)
                .addComponent(txtLOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLUZ)
                    .addComponent(txtLUZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAGUA)
                    .addComponent(txtAGUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkLOCAL)
                    .addComponent(txtLOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel5.setText("hora:");

        lblHORA.setText("jLabel6");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago a Docente"));

        chkDOCENTE.setText("Docente");
        chkDOCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDOCENTEActionPerformed(evt);
            }
        });

        txtDOCENTE.setEditable(false);
        txtDOCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOCENTEActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bonificaciones"));

        cbESTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbESTADOActionPerformed(evt);
            }
        });

        txtBONO.setEditable(false);
        txtBONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBONOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cbESTADO, 0, 97, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtBONO, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Retenciones"));

        chkAFP.setText("AFP 6%");
        chkAFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAFPActionPerformed(evt);
            }
        });

        chkESSALUD.setText("ESSALUD 10%");
        chkESSALUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkESSALUDActionPerformed(evt);
            }
        });

        txtAFP.setEditable(false);
        txtAFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAFPActionPerformed(evt);
            }
        });

        txtESSALUD.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(chkESSALUD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtESSALUD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(chkAFP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAFP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAFP)
                    .addComponent(txtAFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkESSALUD)
                    .addComponent(txtESSALUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setText("Total de pago por 15 Docentes:");

        txtPagoDocente.setEditable(false);

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(chkDOCENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnResolver)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPagoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkDOCENTE)
                            .addComponent(txtDOCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPagoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResolver)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblFECHA)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHORA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbMESES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(172, 172, 172)
                                        .addComponent(jButton1)
                                        .addGap(73, 73, 73)
                                        .addComponent(btnNUEVO))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCALCULAR)
                                        .addGap(148, 148, 148))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(btnSALIR)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFECHA)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbMESES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHORA)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnCALCULAR)
                            .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(btnSALIR)
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNUEVO)
                            .addComponent(jButton1))
                        .addGap(127, 127, 127))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCALCULARActionPerformed
        float docente=0f;
        float afp=0f;
        float essalud=0f;
        float bonificacion=0f;
        float agua=0f;
        float luz=0f;
        float local=0f;
        int bono=cbESTADO.getSelectedIndex();
        float estado=0f;
        float totalapagarmes=0f;
        float totalretencion=0f;
        float boni=0f;
        float pagoDocente=0.0f;
        try {
            luz = Float.parseFloat(txtLUZ.getText());
            agua = Float.parseFloat(txtAGUA.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese solo números en los campos de luz y agua.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return;  // Sale del método si hay una excepción
        }

        switch(bono){
            case 0:
            estado=0f;
            break;
            case 1:
            estado=0.03f;
            break;
            case 2:
            estado=0.05f;
            break;
            case 3:
            estado=0.07f;
            break;
            case 4:
            estado=0.12f;
            break;
            default:
            JOptionPane.showMessageDialog(this, "Seleccione un grado.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);

        }
        if(chkDOCENTE.isSelected()){
            docente=1250;
        }else{
            docente=0;
        }
        if(chkAFP.isSelected()){
            afp=0.06f;
        }else{
            afp=0f;
        }
        if(chkESSALUD.isSelected()){
            essalud=0.10f;
        }else{
            essalud=0;
        }
        if(chkLOCAL.isSelected()){
            local=5000f;
        }else{
            local=0f;
        }
        totalretencion=docente*(afp+essalud);
        boni=docente*estado;
        pagoDocente=(docente+boni-totalretencion)*15;
        totalapagarmes= pagoDocente+local+luz+agua;
        txtTOTAL.setText("S./"+ totalapagarmes);

    }//GEN-LAST:event_btnCALCULARActionPerformed

    private void btnNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNUEVOActionPerformed
        int option = JOptionPane.showConfirmDialog(this,
            "¿desea limpiar formulario?",
            "Confirmar limipiar formulario",
            JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION){
            cbMESES.setSelectedIndex(0);
            cbESTADO.setSelectedIndex(0);
            chkDOCENTE.setSelected(false);
            chkAFP.setSelected(false);
            chkESSALUD.setSelected(false);
            chkLUZ.setSelected(false);
            chkAGUA.setSelected(false);
            chkLOCAL.setSelected(false);
            txtPagoDocente.setText("");
            txtDOCENTE.setText("");
            txtBONO.setText("");
            txtAFP.setText("");
            txtESSALUD.setText("");
            txtAGUA.setText("");
            txtLUZ.setText("");
            txtLOCAL.setText("");
            txtTOTAL.setText("");

        }
    }//GEN-LAST:event_btnNUEVOActionPerformed

    private void btnSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSALIRActionPerformed
        int option = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de salir?",
            "Confirmar salir",
            JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION){

            System.exit(0);

        }
    }//GEN-LAST:event_btnSALIRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int option = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de CALCULAR?",
            "Confirmar CALCULAR",
            JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION){
            int docente =0;

            String luz=txtLUZ.getText();
            String agua=txtAGUA.getText();
            String local=txtLOCAL.getText();
            int meses=cbMESES.getSelectedIndex();
            String mes="";
            String afp=txtAFP.getText();
            String essalud=txtESSALUD.getText();
            int bonificacion=cbESTADO.getSelectedIndex();
            String bono="";
            String pagoDocente = txtPagoDocente.getText();

            String total=txtTOTAL.getText();
            if(chkDOCENTE.isSelected()){
                docente=1250;
            }else{
                docente=0;
            }

            switch(meses){
                case 0:
                mes=null;
                break;
                case 1:
                mes="marzo";
                break;
                case 2:
                mes="abril";
                break;
                case 3:
                mes="mayo";
                break;
                case 4:
                mes="junio";
                break;
                case 5:
                mes="julio";
                break;
                case 6:
                mes="agosto";
                break;
                case 7:
                mes="septiembre";
                break;
                case 8:
                mes="octubre";
                break;
                case 9:
                mes="noviembre";
                break;
                case 10:
                mes="diciembre";
                break;
                default:
                JOptionPane.showMessageDialog(this, "Seleccione un mes.",
                    "Error de entrada", JOptionPane.ERROR_MESSAGE);
            }

            switch(bonificacion){
                case 0:
                bono=null;
                break;
                case 1:
                bono="puntualidad";
                break;
                case 2:
                bono="asistencia";
                break;
                case 3:
                bono="horas extras";
                break;
                default:
                JOptionPane.showMessageDialog(this, "Seleccione un grado.",
                    "Error de entrada", JOptionPane.ERROR_MESSAGE);
            }

            String bonof=txtBONO.getText();

            Date fechaHoraActual = new Date();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy......HH:mm:ss");
            String fechaHora = formatoFecha.format(fechaHoraActual);

            // Aquí puedes agregar el código para mostrar un mensaje de éxito
            if (mes != null && bono != null) {
                String mensajeExito = """
                El pago principal del maestro es:

                """+
                docente+",Soles a cada uno  " +"\n"
                +"La bonificacion es:  "+bonof+";"+"\n"
                + "su afp 6% es: " + afp +";"+ "\n"
                + "su essalud 10% es:  " + essalud +";"+ "\n"
                +"El pago de luz:  S./"+ luz +";"+"\n"
                +"El costo de local es "+local+""+";"+"\n"
                +"El pago de agua es: S./"+agua+";"+"\n"
                +"Total de docentes pagados "+pagoDocente+"\n"
                +"El total general del mes a pagar es: "+ total +"\n"
                +"Fecha y hora de registro:  "+fechaHora+";"+"\n"
                +"Gracias";
                JOptionPane.showMessageDialog(this, mensajeExito, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkLUZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLUZActionPerformed
        float luz=0f;
        if (chkLUZ.isSelected()) {
            // Habilitar el campo de texto
            txtLUZ.setEnabled(true);
            txtLUZ.requestFocus();
        } else {
            // Deshabilitar el campo de texto
            txtLUZ.setEnabled(false);
        }

    }//GEN-LAST:event_chkLUZActionPerformed

    private void chkAGUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAGUAActionPerformed
        float agua=0f;
        if (chkAGUA.isSelected()) {
            // Habilitar el campo de texto
            txtAGUA.setEnabled(true);
            txtAGUA.requestFocus();
        } else {
            // Deshabilitar el campo de texto
            txtAGUA.setEnabled(false);
        }

    }//GEN-LAST:event_chkAGUAActionPerformed

    private void chkLOCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLOCALActionPerformed
        int local=0;
        if(chkLOCAL.isSelected()){
            local=5000;
        }else{
            local=0;
        }
        txtLOCAL.setText("S./"+local);
    }//GEN-LAST:event_chkLOCALActionPerformed

    private void txtLUZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLUZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLUZActionPerformed

    private void chkDOCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDOCENTEActionPerformed
        int docente=0;
        if(chkDOCENTE.isSelected()){
            docente=1250;
        }else{
            docente=0;
        }
        txtDOCENTE.setText("S./"+docente);
    }//GEN-LAST:event_chkDOCENTEActionPerformed

    private void txtDOCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOCENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOCENTEActionPerformed

    private void cbESTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbESTADOActionPerformed
        int estado=cbESTADO.getSelectedIndex();
        float docente=0;
        float bonodocente=0;
        if(chkDOCENTE.isSelected()){
            docente=1250;
        }else{
            docente=0;
        }

        float civil=0f;
        switch(estado){
            case 0:
            civil=0f;
            /**JOptionPane.showMessageDialog(this, "Seleccione un grado.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);**/
            break;
            case 1:
            civil=0.03f;
            break;
            case 2:
            civil=0.05f;
            break;
            case 3:
            civil=0.07f;
            break;
            case 4:
            civil=0.12f;
            break;
            default:
            JOptionPane.showMessageDialog(this, "Seleccione un grado.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);

        }
        bonodocente=docente*civil;
        txtBONO.setText(String.valueOf("S./"+bonodocente));
    }//GEN-LAST:event_cbESTADOActionPerformed

    private void txtBONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBONOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBONOActionPerformed

    private void chkAFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAFPActionPerformed
        float docente=0f;
        float afp=0f;
        float afpdocente=0f;
        if(chkDOCENTE.isSelected()&&chkAFP.isSelected()){
            docente=1250;
            afp=0.06f;
        }else{
            docente=0f;
            afp=0f;
        }
        afpdocente=docente*afp;
        txtAFP.setText("S./"+afpdocente);
    }//GEN-LAST:event_chkAFPActionPerformed

    private void chkESSALUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkESSALUDActionPerformed
        float docente=0f;
        float essalud=0f;
        float essaluddocente=0f;
        if(chkDOCENTE.isSelected()&&chkESSALUD.isSelected()){
            docente=1250;
            essalud=0.10f;
        }else{
            docente=0f;
            essalud=0f;
        }
        essaluddocente=docente*essalud;
        txtESSALUD.setText("S./"+essaluddocente);
    }//GEN-LAST:event_chkESSALUDActionPerformed

    private void txtAFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAFPActionPerformed

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        // TODO add your handling code here:
        float docente=0f;
        float afp=0f;
        float essalud=0f;
        float local=0f;
        int bono=cbESTADO.getSelectedIndex();
        float estado=0f;
        float totalretencion=0f;
        float boni=0f;
        float pagoDocente=0.0f;

        switch(bono){
            case 0:
            estado=0f;
            break;
            case 1:
            estado=0.03f;
            break;
            case 2:
            estado=0.05f;
            break;
            case 3:
            estado=0.07f;
            break;
            case 4:
            estado=0.12f;
            break;
            default:
            JOptionPane.showMessageDialog(this, "Seleccione un grado.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);

        }
        if(chkDOCENTE.isSelected()){
            docente=1250;
        }else{
            docente=0;
        }
        if(chkAFP.isSelected()){
            afp=0.06f;
        }else{
            afp=0f;
        }
        if(chkESSALUD.isSelected()){
            essalud=0.10f;
        }else{
            essalud=0;
        }
        if(chkLOCAL.isSelected()){
            local=5000f;
        }else{
            local=0f;
        }
        totalretencion=docente*(afp+essalud);
        boni=docente*estado;
        pagoDocente=(docente+boni-totalretencion)*15;

        txtPagoDocente.setText("S./"+pagoDocente);

    }//GEN-LAST:event_btnResolverActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        txtLUZ.setEnabled(false);
        txtAGUA.setEnabled(false);
        cbMESES.addItem("elegir...mes");
        cbMESES.addItem("marzo");
        cbMESES.addItem("abril");
        cbMESES.addItem("mayo");
        cbMESES.addItem("junio");
        cbMESES.addItem("julio");
        cbMESES.addItem("agosto");
        cbMESES.addItem("septiembre");
        cbMESES.addItem("octubre");
        cbMESES.addItem("noviembre");
        cbMESES.addItem("diciembre");

        cbESTADO.addItem("elegir");
        cbESTADO.addItem("puntualidad");
        cbESTADO.addItem("asistencia");
        cbESTADO.addItem("horas extras");
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCALCULAR;
    private javax.swing.JButton btnNUEVO;
    private javax.swing.JButton btnResolver;
    private javax.swing.JButton btnSALIR;
    private javax.swing.JComboBox<String> cbESTADO;
    private javax.swing.JComboBox<String> cbMESES;
    private javax.swing.JCheckBox chkAFP;
    private javax.swing.JCheckBox chkAGUA;
    private javax.swing.JCheckBox chkDOCENTE;
    private javax.swing.JCheckBox chkESSALUD;
    private javax.swing.JCheckBox chkLOCAL;
    private javax.swing.JCheckBox chkLUZ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblFECHA;
    private javax.swing.JLabel lblHORA;
    private javax.swing.JTextField txtAFP;
    private javax.swing.JTextField txtAGUA;
    private javax.swing.JTextField txtBONO;
    private javax.swing.JTextField txtDOCENTE;
    private javax.swing.JTextField txtESSALUD;
    private javax.swing.JTextField txtLOCAL;
    private javax.swing.JTextField txtLUZ;
    private javax.swing.JTextField txtPagoDocente;
    private javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
