/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.aea;

/**
 *
 * @author Morales
 */
public class IngresosGanancias extends javax.swing.JInternalFrame {

    /**
     * Creates new form ControlGanancias
     */
    public IngresosGanancias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        chkENERO = new javax.swing.JCheckBox();
        chkFEBRERO = new javax.swing.JCheckBox();
        chkMARZO = new javax.swing.JCheckBox();
        chkABRIL = new javax.swing.JCheckBox();
        chkMAYO = new javax.swing.JCheckBox();
        chkJUNIO = new javax.swing.JCheckBox();
        chkJULIO = new javax.swing.JCheckBox();
        chkAGOSTO = new javax.swing.JCheckBox();
        chkSEPTIEMBRE = new javax.swing.JCheckBox();
        chkOCTUBRE = new javax.swing.JCheckBox();
        chkNOVIEMBRE = new javax.swing.JCheckBox();
        chkDICIEMBRE = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtESTUDIANTES = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCPM = new javax.swing.JTextField();
        txtDESCUENTOPORBECAS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAUMENTO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        chkDIADELPADRE = new javax.swing.JCheckBox();
        chkDIADELAMADRE = new javax.swing.JCheckBox();
        chkPASEOS = new javax.swing.JCheckBox();
        chkANIVERSARIOS = new javax.swing.JCheckBox();
        chkDIADELMAESTRO = new javax.swing.JCheckBox();
        chkOLIMPIADAS = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("INGRESOS/GANANCIAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccionar meses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        chkENERO.setText("ENERO");
        chkENERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkENEROActionPerformed(evt);
            }
        });

        chkFEBRERO.setText("FEBRERO");
        chkFEBRERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFEBREROActionPerformed(evt);
            }
        });

        chkMARZO.setText("MARZO");
        chkMARZO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMARZOActionPerformed(evt);
            }
        });

        chkABRIL.setText("ABRIL");
        chkABRIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkABRILActionPerformed(evt);
            }
        });

        chkMAYO.setText("MAYO");
        chkMAYO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMAYOActionPerformed(evt);
            }
        });

        chkJUNIO.setText("JUNIO");
        chkJUNIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJUNIOActionPerformed(evt);
            }
        });

        chkJULIO.setText("JULIO");
        chkJULIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJULIOActionPerformed(evt);
            }
        });

        chkAGOSTO.setText("AGOSTO");
        chkAGOSTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAGOSTOActionPerformed(evt);
            }
        });

        chkSEPTIEMBRE.setText("SEPTIEMBRE");
        chkSEPTIEMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSEPTIEMBREActionPerformed(evt);
            }
        });

        chkOCTUBRE.setText("OCTUBRE");
        chkOCTUBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOCTUBREActionPerformed(evt);
            }
        });

        chkNOVIEMBRE.setText("NOVIEMBRE");
        chkNOVIEMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNOVIEMBREActionPerformed(evt);
            }
        });

        chkDICIEMBRE.setText("DICIEMBRE");
        chkDICIEMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDICIEMBREActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkJULIO)
                    .addComponent(chkENERO))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFEBRERO)
                    .addComponent(chkAGOSTO))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkMARZO)
                        .addGap(18, 18, 18)
                        .addComponent(chkABRIL))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkSEPTIEMBRE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkOCTUBRE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(chkNOVIEMBRE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkDICIEMBRE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(chkMAYO)
                        .addGap(46, 46, 46)
                        .addComponent(chkJUNIO)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkENERO)
                    .addComponent(chkFEBRERO)
                    .addComponent(chkMARZO)
                    .addComponent(chkABRIL)
                    .addComponent(chkMAYO)
                    .addComponent(chkJUNIO))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkJULIO)
                    .addComponent(chkAGOSTO)
                    .addComponent(chkSEPTIEMBRE)
                    .addComponent(chkOCTUBRE)
                    .addComponent(chkNOVIEMBRE)
                    .addComponent(chkDICIEMBRE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("MOSTRAR "));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula"));

        jLabel2.setText("Cantidad de estudiantes:");

        txtESTUDIANTES.setEditable(false);

        jLabel3.setText("Cargos por mora:");

        jLabel4.setText("Descuento por becas:");

        txtCPM.setEditable(false);

        txtDESCUENTOPORBECAS.setEditable(false);

        jLabel5.setText("Total:");

        txtTOTAL.setEditable(false);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Aumento por Festividad:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("*Mora=S/20*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtESTUDIANTES, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCPM, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDESCUENTOPORBECAS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtAUMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtESTUDIANTES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(76, 76, 76)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAUMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDESCUENTOPORBECAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnNuevo)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnNuevo)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccionar Festividad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        chkDIADELPADRE.setText("Dia del Padre");
        chkDIADELPADRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDIADELPADREActionPerformed(evt);
            }
        });

        chkDIADELAMADRE.setText("Dia de la Madre");
        chkDIADELAMADRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDIADELAMADREActionPerformed(evt);
            }
        });

        chkPASEOS.setText("Paseos");
        chkPASEOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPASEOSActionPerformed(evt);
            }
        });

        chkANIVERSARIOS.setText("Aniversarios");
        chkANIVERSARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkANIVERSARIOSActionPerformed(evt);
            }
        });

        chkDIADELMAESTRO.setText("Dia del Maestro");
        chkDIADELMAESTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDIADELMAESTROActionPerformed(evt);
            }
        });

        chkOLIMPIADAS.setText("Olimpiadas");
        chkOLIMPIADAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOLIMPIADASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(chkDIADELPADRE)
                        .addGap(43, 43, 43)
                        .addComponent(chkDIADELAMADRE)
                        .addGap(52, 52, 52)
                        .addComponent(chkPASEOS)
                        .addGap(49, 49, 49)
                        .addComponent(chkANIVERSARIOS))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(chkDIADELMAESTRO)
                        .addGap(48, 48, 48)
                        .addComponent(chkOLIMPIADAS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDIADELPADRE)
                    .addComponent(chkDIADELAMADRE)
                    .addComponent(chkPASEOS)
                    .addComponent(chkANIVERSARIOS))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDIADELMAESTRO)
                    .addComponent(chkOLIMPIADAS))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ingresos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkOLIMPIADASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOLIMPIADASActionPerformed
        int olimpiadas=0;
        if(chkOLIMPIADAS.isSelected()){
            olimpiadas=450;
        }else{
            olimpiadas=0;
        }
        txtAUMENTO.setText("S/"+olimpiadas);     // TODO add your handling code here:
    }//GEN-LAST:event_chkOLIMPIADASActionPerformed

    private void chkDIADELMAESTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDIADELMAESTROActionPerformed
        int maestro=0;
        if(chkDIADELMAESTRO.isSelected()){
            maestro=100;
        }else{
            maestro=0;
        }
        txtAUMENTO.setText("S/"+maestro);
    }//GEN-LAST:event_chkDIADELMAESTROActionPerformed

    private void chkANIVERSARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkANIVERSARIOSActionPerformed
        int aniversarios=0;
        if(chkANIVERSARIOS.isSelected()){
            aniversarios=300;
        }else{
            aniversarios=0;
        }
        txtAUMENTO.setText("S/"+aniversarios);
    }//GEN-LAST:event_chkANIVERSARIOSActionPerformed

    private void chkPASEOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPASEOSActionPerformed
        int paseos=0;
        if(chkPASEOS.isSelected()){
            paseos=500;
        }else{
            paseos=0;
        }
        txtAUMENTO.setText("S/"+paseos);
    }//GEN-LAST:event_chkPASEOSActionPerformed

    private void chkDIADELAMADREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDIADELAMADREActionPerformed
        int madre=0;
        if(chkDIADELAMADRE.isSelected()){
            madre=150;
        }else{
            madre=0;
        }
        txtAUMENTO.setText("S/"+madre);
    }//GEN-LAST:event_chkDIADELAMADREActionPerformed

    private void chkDIADELPADREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDIADELPADREActionPerformed
        int padre=0;
        if(chkDIADELPADRE.isSelected()){
            padre=150;
        }else{
            padre=0;
        }
        txtAUMENTO.setText("S/"+padre);   // TODO add your handling code here:
    }//GEN-LAST:event_chkDIADELPADREActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float estudiantes=0f;
        float festividad=0f;
        float becas=0f;
        float mora=0f;
        float total=0f;
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkDICIEMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDICIEMBREActionPerformed
        int diciembre=0;
        if(chkDICIEMBRE.isSelected()){
            diciembre=22;
        }else{
            diciembre=0;
        }
        txtESTUDIANTES.setText(""+diciembre);

        int cpm=0;
        if(chkDICIEMBRE.isSelected()){
            cpm=80;
        }else{
            diciembre=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkDICIEMBREActionPerformed

    private void chkNOVIEMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNOVIEMBREActionPerformed
        int noviembre=0;
        if(chkNOVIEMBRE.isSelected()){
            noviembre=22;
        }else{
            noviembre=0;
        }
        txtESTUDIANTES.setText(""+noviembre);

        int cpm=0;
        if(chkNOVIEMBRE.isSelected()){
            cpm=20;
        }else{
            noviembre=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkNOVIEMBREActionPerformed

    private void chkOCTUBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOCTUBREActionPerformed
        int octubre=0;
        if(chkOCTUBRE.isSelected()){
            octubre=20;
        }else{
            octubre=0;
        }
        txtESTUDIANTES.setText(""+octubre);

        int cpm=0;
        if(chkOCTUBRE.isSelected()){
            cpm=60;
        }else{
            octubre=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkOCTUBREActionPerformed

    private void chkSEPTIEMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSEPTIEMBREActionPerformed
        int septiembre=0;
        if(chkSEPTIEMBRE.isSelected()){
            septiembre=21;
        }else{
            septiembre=0;
        }
        txtESTUDIANTES.setText(""+septiembre);

        int cpm=0;
        if(chkSEPTIEMBRE.isSelected()){
            cpm=40;
        }else{
            septiembre=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkSEPTIEMBREActionPerformed

    private void chkAGOSTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAGOSTOActionPerformed
        int agosto=0;
        if(chkAGOSTO.isSelected()){
            agosto=20;
        }else{
            agosto=0;
        }
        txtESTUDIANTES.setText(""+agosto);

        int cpm=0;
        if(chkAGOSTO.isSelected()){
            cpm=100;
        }else{
            agosto=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkAGOSTOActionPerformed

    private void chkJULIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJULIOActionPerformed
        int julio=0;
        if(chkJULIO.isSelected()){
            julio=22;
        }else{
            julio=0;
        }
        txtESTUDIANTES.setText(""+julio);

        int cpm=0;
        if(chkJULIO.isSelected()){
            cpm=40;
        }else{
            julio=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkJULIOActionPerformed

    private void chkJUNIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJUNIOActionPerformed
        int junio=0;
        if(chkJUNIO.isSelected()){
            junio=22;
        }else{
            junio=0;
        }
        txtESTUDIANTES.setText(""+junio);

        int cpm=0;
        if(chkJUNIO.isSelected()){
            cpm=20;
        }else{
            junio=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkJUNIOActionPerformed

    private void chkMAYOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMAYOActionPerformed
        int mayo=0;
        if(chkMAYO.isSelected()){
            mayo=20;
        }else{
            mayo=0;
        }
        txtESTUDIANTES.setText(""+mayo);

        int cpm=0;
        if(chkMAYO.isSelected()){
            cpm=60;
        }else{
            mayo=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkMAYOActionPerformed

    private void chkABRILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkABRILActionPerformed
        int abril=0;
        if(chkABRIL.isSelected()){
            abril=20;
        }else{
            abril=0;
        }
        txtESTUDIANTES.setText(""+abril);

        int cpm=0;
        if(chkABRIL.isSelected()){
            cpm=40;
        }else{
            abril=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkABRILActionPerformed

    private void chkMARZOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMARZOActionPerformed
        int marzo=0;
        if(chkMARZO.isSelected()){
            marzo=21;
        }else{
            marzo=0;
        }
        txtESTUDIANTES.setText(""+marzo);

        int cpm=0;
        if(chkMARZO.isSelected()){
            cpm=40;
        }else{
            marzo=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkMARZOActionPerformed

    private void chkFEBREROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFEBREROActionPerformed
        int febrero=0;
        if(chkFEBRERO.isSelected()){
            febrero=25;
        }else{
            febrero=0;
        }
        txtESTUDIANTES.setText(""+febrero);

        int cpm=0;
        if(chkFEBRERO.isSelected()){
            cpm=60;
        }else{
            febrero=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkFEBREROActionPerformed

    private void chkENEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkENEROActionPerformed
        int enero=0;
        if(chkENERO.isSelected()){
            enero=17;
        }else{
            enero=0;
        }
        txtESTUDIANTES.setText(""+enero);

        int cpm=0;
        if(chkENERO.isSelected()){
            cpm=120;
        }else{
            enero=0;
        }
        txtCPM.setText("S/"+cpm);
    }//GEN-LAST:event_chkENEROActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        chkENERO.setSelected(false);
        chkFEBRERO.setSelected(false);
        chkMARZO.setSelected(false);
        chkABRIL.setSelected(false);
        chkMAYO.setSelected(false);
        chkJUNIO.setSelected(false);
        chkJULIO.setSelected(false);
        chkAGOSTO.setSelected(false);
        chkSEPTIEMBRE.setSelected(false);
        chkOCTUBRE.setSelected(false);
        chkNOVIEMBRE.setSelected(false);
        chkDICIEMBRE.setSelected(false);
        chkDIADELPADRE.setSelected(false);
        chkDIADELAMADRE.setSelected(false);
        chkPASEOS.setSelected(false);
        chkANIVERSARIOS.setSelected(false);
        chkDIADELMAESTRO.setSelected(false);
        chkOLIMPIADAS.setSelected(false);
        txtESTUDIANTES.setText("");
        txtAUMENTO.setText("");
        txtDESCUENTOPORBECAS.setText("");
        txtCPM.setText("");
        txtTOTAL.setText("");
        
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkABRIL;
    private javax.swing.JCheckBox chkAGOSTO;
    private javax.swing.JCheckBox chkANIVERSARIOS;
    private javax.swing.JCheckBox chkDIADELAMADRE;
    private javax.swing.JCheckBox chkDIADELMAESTRO;
    private javax.swing.JCheckBox chkDIADELPADRE;
    private javax.swing.JCheckBox chkDICIEMBRE;
    private javax.swing.JCheckBox chkENERO;
    private javax.swing.JCheckBox chkFEBRERO;
    private javax.swing.JCheckBox chkJULIO;
    private javax.swing.JCheckBox chkJUNIO;
    private javax.swing.JCheckBox chkMARZO;
    private javax.swing.JCheckBox chkMAYO;
    private javax.swing.JCheckBox chkNOVIEMBRE;
    private javax.swing.JCheckBox chkOCTUBRE;
    private javax.swing.JCheckBox chkOLIMPIADAS;
    private javax.swing.JCheckBox chkPASEOS;
    private javax.swing.JCheckBox chkSEPTIEMBRE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAUMENTO;
    private javax.swing.JTextField txtCPM;
    private javax.swing.JTextField txtDESCUENTOPORBECAS;
    private javax.swing.JTextField txtESTUDIANTES;
    private javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
