package com.mycompany.aea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */


/**
 *
 * @author Jhordan
 */
import java.util.HashSet;
import java.util.Set;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class Matricula extends javax.swing.JInternalFrame {
    private DefaultListModel<String> lista = new DefaultListModel<>();
    private Set<String> nombresSet = new HashSet<>();
    DefaultListModel especial = new DefaultListModel();
    DefaultListModel nivel1 = new DefaultListModel();
    DefaultListModel codigo = new DefaultListModel();
    DefaultListModel Acuenta = new DefaultListModel();
    DefaultListModel Pension = new DefaultListModel();
    DefaultListModel Saldo = new DefaultListModel();
    DefaultListModel habilidad = new DefaultListModel();
    DefaultListModel seccion = new DefaultListModel();
    DefaultListModel grado = new DefaultListModel();

    /**
     * Creates new form Matricula
     */
    public Matricula() {
        initComponents();
        
    deshabilitarComponentes();
    btnIngresar.setEnabled(false);
    btnQuitar.setEnabled(false);
    
    

    verificarCampos(); 
    DNI();
    }
    
    private void deshabilitarComponentes() {
    txtDNI.setEnabled(false);
    txtApellido.setEnabled(false);
    txtNombre.setEnabled(false);
    cbSexo.setEnabled(false);
    cbEdad.setEnabled(false);
    cbHabilidad.setEnabled(false);
    cbTurno.setEnabled(false);
    chkBeca.setEnabled(false);
    cbSeccion.setEnabled(false);
    cbGrado.setEnabled(false);
    txtAcuenta.setEnabled(false);
    chkProrroga.setEnabled(false);
    lstCodigo.setEnabled(false);
    lstname.setEnabled(false);
    lstSeccion.setEnabled(false);
    ;
    lstPension.setEnabled(false);
    lstDscto.setEnabled(false);
    lstSaldo.setEnabled(false);
    txtTotalAlumnos.setEnabled(false);
    txtPension.setEnabled(false);
    txtDscto.setEnabled(false);
    txtSaldo.setEnabled(false);

    Enumeration<AbstractButton> buttons = buttonGroup1.getElements();
    while (buttons.hasMoreElements()) {
        AbstractButton button = buttons.nextElement();
        button.setEnabled(false);
    }
}   

    private void DNI(){
        int indexEdad = cbEdad.getSelectedIndex();
        if(indexEdad >=4){
            txtDNI.setEnabled(true);
        }else{
            txtDNI.setEnabled(false);
        }

    }
    
    private void verificarCampos() {
    // Verificar el JComboBox
    int indexSexo = cbSexo.getSelectedIndex();
    int indexEdad = cbEdad.getSelectedIndex();
    int indexTurno = cbTurno.getSelectedIndex();
    int indexSeccion = cbSeccion.getSelectedIndex();
    int indexGrado = cbGrado.getSelectedIndex();
    
    // Verificar campos de texto y el valor del JComboBox
    if (/**(chkBeca.isSelected() || chkProrroga.isSelected())&&**/(indexSexo !=0 && indexEdad !=0 && indexTurno !=0) &&
        /**!txtDNI.getText().isEmpty() &&**/
        !txtApellido.getText().isEmpty() &&
        /**!txtAcuenta.getText().isEmpty() &&**/
        !txtNombre.getText().isEmpty()&& cbSeccion.getSelectedIndex()!=0 && cbGrado.getSelectedIndex()!=0/**&&(rbNivel1.isSelected() || rbNivel2.isSelected())**/) {
        // Habilitar el botón si el JComboBox está en el caso 1 o 2 y los campos de texto no están vacíos
        btnIngresar.setEnabled(true);
    } else {
        // Si no cumple las condiciones anteriores, deshabilitar el botón
        btnIngresar.setEnabled(false);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        cbEdad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbTurno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        chkBeca = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtAcuenta = new javax.swing.JTextField();
        chkProrroga = new javax.swing.JCheckBox();
        cbHabilidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbSeccion = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        cbGrado = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        txtSaldo = new javax.swing.JTextField();
        btnQuitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPension = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstDscto = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstSaldo = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCodigo = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotalAlumnos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstname = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        txtPension = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSeccion = new javax.swing.JList<>();
        txtDscto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstHabilidad = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstGrado = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("MATRICULA DE ALUMNOS");

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });
        cbSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbSexoKeyReleased(evt);
            }
        });

        cbEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEdadActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Nro  DNI:");

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDNIKeyReleased(evt);
            }
        });

        jLabel7.setText("habilidad");

        jLabel9.setText("Turno:");

        cbTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurnoActionPerformed(evt);
            }
        });

        jLabel10.setText("Becado:");

        chkBeca.setText("Beca Integral");
        chkBeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBecaActionPerformed(evt);
            }
        });
        chkBeca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chkBecaKeyReleased(evt);
            }
        });

        jLabel11.setText("Acuenta:");

        txtAcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcuentaActionPerformed(evt);
            }
        });
        txtAcuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAcuentaKeyReleased(evt);
            }
        });

        chkProrroga.setText("Prorroga");
        chkProrroga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProrrogaActionPerformed(evt);
            }
        });

        jLabel8.setText("Seccion:");

        jLabel22.setText("Grado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chkBeca))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbHabilidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(chkProrroga))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(cbGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(cbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(chkBeca)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbHabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkProrroga)
                            .addComponent(txtAcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");

        lstPension.setEnabled(false);
        jScrollPane5.setViewportView(lstPension);

        lstDscto.setEnabled(false);
        jScrollPane6.setViewportView(lstDscto);

        lstSaldo.setEnabled(false);
        jScrollPane8.setViewportView(lstSaldo);

        jLabel14.setText("Seccion");

        jLabel15.setText("Especialidad");

        jLabel16.setText("Pension");

        jLabel17.setText("Dscto");

        jLabel12.setText("Nro");

        lstCodigo.setEnabled(false);
        jScrollPane1.setViewportView(lstCodigo);

        jLabel19.setText("Saldo");

        jLabel20.setText("Total Alumnos:");

        jLabel13.setText("Apellidos y Nombres");

        lstname.setEnabled(false);
        lstname.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lstnameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstnameKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(lstname);

        jLabel21.setText("Totales:  ====>>");

        lstSeccion.setEnabled(false);
        jScrollPane3.setViewportView(lstSeccion);

        lstHabilidad.setEnabled(false);
        jScrollPane4.setViewportView(lstHabilidad);

        jScrollPane9.setViewportView(lstGrado);

        jLabel23.setText("Grado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel12)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel13)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel14)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel23)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel15)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel16)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel20)
                                .addGap(36, 36, 36)
                                .addComponent(txtTotalAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel21)
                                .addGap(50, 50, 50)
                                .addComponent(txtPension, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDscto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNuevo)
                            .addComponent(btnIngresar)
                            .addComponent(btnQuitar)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19)
                                .addComponent(btnSalir)))))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitar)
                        .addGap(27, 27, 27)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel23)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtPension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDscto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int numeroCorrelativo = 0;
    private int totalAlumnos = 0;
    private int totalPension = 0;
    private int totalDescuento = 0;
    private int totalSaldo = 0;
    
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
float descuento = 0f;
    float pension = 520f;
    float saldo = 0f;

    // Verificar si txtAcuenta está habilitado
    if (txtAcuenta.isEnabled()) {
        try {
            // Intentar obtener el valor de txtAcuenta como un número flotante
            descuento = Float.parseFloat(txtAcuenta.getText());
        } catch (NumberFormatException e) {
            // Manejar la excepción si el texto no es un número válido
            manejarNumberFormatException("Ingrese un número válido en txtAcuenta");
            return;
        }
    }

    if (chkBeca.isSelected()) {
        // Si hay beca, la pensión es cero
        pension = 0f;
    }

    saldo = pension - descuento;

    // Método para obtener el nivel seleccionado
    String nuevoNombreCompleto = this.txtApellido.getText() + " " + this.txtNombre.getText();
        int secc = cbSeccion.getSelectedIndex();
        String re = null;
        switch(secc){
            case 0:
                re = null;
                break;
            case 1:
                re = "A";
                break;
            case 2:
                re = "B";
                break;
            case 3:
                re = "C";
                break;
            default:
                return;
        }
    int grad = cbGrado.getSelectedIndex();
    String gd = null;
        switch(grad){
            case 0:
                gd = null;
                break;
            case 1:
                gd = "1er Grado";
                break;
            case 2:
                gd = "2do Grado";
                break;
            case 3:
                gd = "3er Grado";
                break;
            case 4:
                gd = "4to Grado";
                break;
            case 5:
                gd = "5to Grado";
                break;
            default:
                return;
        }

    // Verificar si el nombre y apellido ya están en la lista
    if (!lista.contains(nuevoNombreCompleto)) {
        // El nombre y apellido no están en la lista, agregarlos
        lista.addElement(nuevoNombreCompleto);
        Saldo.addElement("S/." + saldo);
        Pension.addElement("S/." + pension);
        Acuenta.addElement("S/." + descuento);
        codigo.addElement(generarCorrelativo() + " - ");
        seccion.addElement(re);
        grado.addElement(gd);
        // Incrementar el conteo de alumnos
        totalAlumnos++;
        totalPension += pension;
        totalDescuento += descuento;
        totalSaldo += saldo;

        // Actualizar el campo de texto con el total
        actualizarTotales();

        // Establecer modelos en las listas
        this.lstname.setModel(lista);

        // Habilitar o deshabilitar el botón "Quitar" según si la lista está vacía
        btnQuitar.setEnabled(!lista.isEmpty());

    } else {
        // El nombre y apellido ya están en la lista
        // Mostrar un mensaje de error con JOptionPane
        JOptionPane.showMessageDialog(null, "Error: Nombre y apellido repetidos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Establecer modelos en las demás listas
    this.lstSaldo.setModel(Saldo);
    this.lstPension.setModel(Pension);
    this.lstDscto.setModel(Acuenta);
    this.lstCodigo.setModel(codigo);
    this.lstSeccion.setModel(seccion);
    this.lstGrado.setModel(grado);
    

    // Obtener la especialidad seleccionada
    String especialidad = obtenerEspecialidadSeleccionada();

    // Mostrar la especialidad en lstHabilidad
    
    habilidad.addElement(especialidad);
    this.lstHabilidad.setModel(habilidad);
    lstHabilidad.setVisible(true);

    // Habilitar o deshabilitar el botón "Quitar" según si la lista está vacía
    btnQuitar.setEnabled(!lista.isEmpty());
            
    }//GEN-LAST:event_btnIngresarActionPerformed

   private void manejarNumberFormatException(String mensajeError) {
    System.err.println("Error: " + mensajeError);
    JOptionPane.showMessageDialog(this, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
    txtAcuenta.setText("");
}

private void actualizarTotales() {
    this.txtSaldo.setText(Integer.toString(totalSaldo));
    this.txtDscto.setText(Integer.toString(totalDescuento));
    this.txtTotalAlumnos.setText(Integer.toString(totalAlumnos));
    this.txtPension.setText(Integer.toString(totalPension));
}

private String obtenerEspecialidadSeleccionada() {
    int especialidadIndex = cbHabilidad.getSelectedIndex();
    String especialidad = null;

    switch (especialidadIndex) {
        case 0:
            especialidad = "Seleccionar habilidad";
            break;
        case 1:
            especialidad = "Arte";
            break;
        case 2:
            especialidad = "Deporte";
            break;
        case 3:
            especialidad = "Razonamiento Matematico";
            break;
    }

    return especialidad;
} 
    
    private String generarCorrelativo() {
    // Incrementar el número correlativo y formatear para tener dos dígitos
    numeroCorrelativo = (numeroCorrelativo % 25) + 1; // Reinicia si llega a 99
    return String.format("%02d", numeroCorrelativo);
}
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        JComboBox<String> lstEspecialidad = new JComboBox<>();

        // Agregar el elemento "Elegir.." al principio

        cbSexo.addItem("Elegir Sexo...");
        cbSexo.addItem("Masculino");
        cbSexo.addItem("Femenino");
        cbEdad.addItem("Elegir Edad...");
        cbEdad.addItem("12");
        cbEdad.addItem("13");
        cbEdad.addItem("14");
        cbEdad.addItem("15");
        cbEdad.addItem("16");
        cbEdad.addItem("17");
        cbEdad.addItem("18");
        cbTurno.addItem("Elegir turno...");
        cbTurno.addItem("Mañana");
        cbTurno.addItem("Tarde");
        cbTurno.addItem("Noche");
        cbSeccion.addItem("Elegir seccion");
        cbSeccion.addItem("A");
        cbSeccion.addItem("B");
        cbSeccion.addItem("C");
        cbGrado.addItem("Elegir grado");
        cbGrado.addItem("1er Grado");
        cbGrado.addItem("2er Grado");
        cbGrado.addItem("3er Grado");
        cbGrado.addItem("4er Grado");
        cbGrado.addItem("5er Grado");
        cbHabilidad.addItem("Seleccionar habilidad");
        cbHabilidad.addItem("Arte");
        cbHabilidad.addItem("Deporte");
        cbHabilidad.addItem("Razonamiento Matematico");
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        cbSeccion.setEnabled(true);
        cbGrado.setEnabled(true);
        txtApellido.setEnabled(true);
        txtNombre.setEnabled(true);
        cbSexo.setEnabled(true);
        cbEdad.setEnabled(true);
        cbTurno.setEnabled(true);
        chkBeca.setEnabled(true);
        txtAcuenta.setEnabled(true);
        chkProrroga.setEnabled(true);
        lstCodigo.setEnabled(true);
        lstHabilidad.setEnabled(true);
        lstname.setEnabled(true);
        lstSeccion.setEnabled(true);
        lstPension.setEnabled(true);
        lstDscto.setEnabled(true);
        lstSaldo.setEnabled(true);
        txtTotalAlumnos.setEnabled(true);
        txtPension.setEnabled(true);
        txtDscto.setEnabled(true);
        txtSaldo.setEnabled(true);
        cbHabilidad.setEnabled(false);
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtDNI.setText("");
        cbHabilidad.setSelectedIndex(0);
        txtAcuenta.setText("");
        cbSexo.setSelectedIndex(0);
        cbEdad.setSelectedIndex(0);
        cbTurno.setSelectedIndex(0);
        chkBeca.setSelected(false);
        chkProrroga.setSelected(false);
        buttonGroup1.clearSelection();
        cbSeccion.setSelectedIndex(0);
        cbGrado.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        // TODO add your handling code here:
        verificarCampos();
        
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        verificarCampos();
        
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyReleased
        // TODO add your handling code here:
     String texto = txtDNI.getText();
    
    // Limpiar el campo de cualquier caracter no numérico
    StringBuilder sb = new StringBuilder();
    for (char c : texto.toCharArray()) {
        if (Character.isDigit(c)) {
            sb.append(c);
        } else {
            // Mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, ingrese solo números.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Establecer el texto limpio en el campo
    txtDNI.setText(sb.toString());
    
    // Llamar a la función de verificación de campos
    verificarCampos();
    }//GEN-LAST:event_txtDNIKeyReleased

    private void txtAcuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcuentaKeyReleased
        // TODO add your handling code here:
        try {
        float acuenta = Float.parseFloat(txtAcuenta.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Ingrese un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        txtAcuenta.setText("");
    }
        
        
        
    verificarCampos();
    }//GEN-LAST:event_txtAcuentaKeyReleased

    private void cbSexoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSexoKeyReleased
        // TODO add your handling code here:      
    }//GEN-LAST:event_cbSexoKeyReleased

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        verificarCampos();
    }//GEN-LAST:event_cbSexoActionPerformed

    private void cbEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEdadActionPerformed
        // TODO add your handling code here:
        DNI();
    verificarCampos();
    }//GEN-LAST:event_cbEdadActionPerformed

    private void cbTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurnoActionPerformed
        // TODO add your handling code here:
        verificarCampos();
    }//GEN-LAST:event_cbTurnoActionPerformed

    private void chkBecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBecaActionPerformed
        // TODO add your handling code here:
        if(chkBeca.isSelected()){
            txtAcuenta.setEnabled(false);
            chkProrroga.setEnabled(false);
            cbHabilidad.setEnabled(true);
        }else{
            txtAcuenta.setEnabled(true);
            chkProrroga.setEnabled(true);
            cbHabilidad.setEnabled(false);
        }
        verificarCampos();
    }//GEN-LAST:event_chkBecaActionPerformed

    private void chkProrrogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProrrogaActionPerformed
        // TODO add your handling code here:
        if(chkProrroga.isSelected()){
            txtAcuenta.setEnabled(false);
        }else{
            txtAcuenta.setEnabled(true);
        }
        verificarCampos();
    }//GEN-LAST:event_chkProrrogaActionPerformed

    private void lstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstnameKeyReleased
        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_lstnameKeyReleased

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        int selectedIndex = lstname.getSelectedIndex();

    // Verificar si se ha seleccionado una fila
    if (selectedIndex != -1) {
        // Obtener el elemento seleccionado
        String selectedName = lista.getElementAt(selectedIndex);

        // Eliminar el elemento de cada modelo de lista
        lista.removeElementAt(selectedIndex);
        Saldo.removeElementAt(selectedIndex);
        Pension.removeElementAt(selectedIndex);
        Acuenta.removeElementAt(selectedIndex);
        codigo.removeElementAt(selectedIndex);
        nivel1.removeElementAt(selectedIndex);
        especial.removeElementAt(selectedIndex);

        // Establecer los nuevos modelos en las listas
        this.lstname.setModel(lista);
        this.lstSaldo.setModel(Saldo);
        this.lstPension.setModel(Pension);
        this.lstDscto.setModel(Acuenta);
        this.lstCodigo.setModel(codigo);
        this.lstSeccion.setModel(nivel1);
        this.lstHabilidad.setModel(especial);

        // Habilitar o deshabilitar el botón "Quitar" según si la lista está vacía
        btnQuitar.setEnabled(!lista.isEmpty());

        // Resto de tu código después de quitar el elemento...
    } else {
        // No se ha seleccionado ninguna fila, puedes mostrar un mensaje de error o realizar otras acciones si es necesario
        JOptionPane.showMessageDialog(null, "Error: Seleccionar la fila a travez del apellido y nombre", "Error", JOptionPane.ERROR_MESSAGE);
        
    }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtAcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcuentaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAcuentaActionPerformed

    private void lstnameActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    } 
    
    private void lstnameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lstnameAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lstnameAncestorAdded

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtDNIActionPerformed

    private void chkBecaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkBecaKeyReleased
        // TODO add your handling code here:
        if(chkBeca.isSelected()){
            txtAcuenta.setEnabled(false);
            chkProrroga.setEnabled(false);
            cbHabilidad.setEnabled(true);
        }else{
            txtAcuenta.setEnabled(true);
            chkProrroga.setEnabled(true);
            cbHabilidad.setEnabled(false);
        }
    }//GEN-LAST:event_chkBecaKeyReleased

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEdad;
    private javax.swing.JComboBox<String> cbGrado;
    private javax.swing.JComboBox<String> cbHabilidad;
    private javax.swing.JComboBox<String> cbSeccion;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cbTurno;
    private javax.swing.JCheckBox chkBeca;
    private javax.swing.JCheckBox chkProrroga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> lstCodigo;
    private javax.swing.JList<String> lstDscto;
    private javax.swing.JList<String> lstGrado;
    private javax.swing.JList<String> lstHabilidad;
    private javax.swing.JList<String> lstPension;
    private javax.swing.JList<String> lstSaldo;
    private javax.swing.JList<String> lstSeccion;
    private javax.swing.JList<String> lstname;
    private javax.swing.JTextField txtAcuenta;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDscto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPension;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTotalAlumnos;
    // End of variables declaration//GEN-END:variables
}
