/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.aea;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Morales
 */

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.*;
public class RegistroDeEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroDeEmpleados
     */
    private DefaultListModel<String> listaEmpleado = new DefaultListModel<>();
    DefaultListModel<String> CodigoEmpleado = new DefaultListModel();
    DefaultListModel<String> NombreEmpleado = new DefaultListModel();
    DefaultListModel<String> CorreoEmpleado = new DefaultListModel();
    DefaultListModel<String> SexoEmpleado = new DefaultListModel();
    DefaultListModel<String> SeccionEmpleado = new DefaultListModel();
    DefaultListModel<String> GradoEmpleado = new DefaultListModel();
    DefaultListModel<String> TelefonoEmpleado = new DefaultListModel();
    DefaultListModel<String> EspecialidadEmpleado = new DefaultListModel();
    
    
    private final String dni;
    public RegistroDeEmpleados(String dni) {
        this.dni = dni;
        initComponents();
        mostrarValor();
    }
    private void mostrarValor() {
        // Mostrar el valor en el JTextField u otro componente según tus necesidades
        txtDNI.setText(dni);
    }

    
    
    
    public RegistroDeEmpleados() {
        initComponents();
        this.dni = null;
    }
    

    RegistroDeEmpleados(DefaultListModel<String> DNI) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private boolean validarCamposVacios() {
    if (txtApellido.getText().trim().isEmpty()|| txtNombre.getText().trim().isEmpty()
            || txtDireccion.getText().trim().isEmpty()            
            || txtCorreo.getText().trim().isEmpty()|| txtDNI.getText().trim().isEmpty()
            || txtTelefono.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Este campo es requerido",
                "Error", JOptionPane.ERROR_MESSAGE);
        return false;
        }   
        return true; 
    }
    private boolean GradoCursoSeccion(){
        if(cbGrado.getSelectedIndex()==0 || cbEspecialidad.getSelectedIndex()==0 || cbSeccion.getSelectedIndex()==0
                || cbEstado.getSelectedIndex()==0){
        }
        return false;
    }
    
    
    
    private int totalMasculinoEmpleado = 0;
    private int totalFemeninoEmpleado = 0;
    private int totalCasadoEmpleado = 0;
    private int totalSolterosEmpleado = 0;
    private int totalViudosEmpleado = 0;
    private int totalDivorciadosEmpleado = 0;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegistroDeClientes = new javax.swing.JTabbedPane();
        sds = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnCodigo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        cbGrado = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        cbSeccion = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCodigo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNombre = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSeccion = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstCorreo = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstGrado = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstTelefono = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstSexo = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstEspecialidad = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTotalMas = new javax.swing.JTextField();
        txtTotalFem = new javax.swing.JTextField();
        txtTotalCas = new javax.swing.JTextField();
        txtTotalSolt = new javax.swing.JTextField();
        txtTotalViu = new javax.swing.JTextField();
        txtTotalDiv = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE EMPLEADOS");

        btnEnviar.setText("ENVIAR DATOS");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado Civil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEstado, 0, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setText("Codigo:");

        txtCodigo.setEditable(false);

        btnCodigo.setText("Generar");
        btnCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Puesto de Trabajo"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEXO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        rbMasculino.setText("Masculino");

        rbFemenino.setText("Femenino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMasculino)
                .addGap(18, 18, 18)
                .addComponent(rbFemenino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Del Empleado"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("DNI:");

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDNIKeyReleased(evt);
            }
        });

        jLabel27.setText("Correo:");

        jLabel28.setText("Direccion:");

        jLabel29.setText("Telefono:");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel29))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel27))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo)
                    .addComponent(txtDNI)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguro"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(cbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(cbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sdsLayout = new javax.swing.GroupLayout(sds);
        sds.setLayout(sdsLayout);
        sdsLayout.setHorizontalGroup(
            sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdsLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCodigo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sdsLayout.createSequentialGroup()
                .addGroup(sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sdsLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sdsLayout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(sdsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(sdsLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        sdsLayout.setVerticalGroup(
            sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sdsLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(sdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCodigo)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        RegistroDeClientes.addTab("DATOS DEL EMPLEADO", sds);

        jLabel5.setText("Codigo");

        lstCodigo.setEnabled(false);
        jScrollPane1.setViewportView(lstCodigo);

        lstNombre.setEnabled(false);
        jScrollPane2.setViewportView(lstNombre);

        lstSeccion.setEnabled(false);
        jScrollPane3.setViewportView(lstSeccion);

        lstCorreo.setEnabled(false);
        jScrollPane5.setViewportView(lstCorreo);

        jLabel6.setText("Nombres y Apellidos");

        jLabel7.setText("Seguro");

        jLabel8.setText("Sexo");

        jLabel9.setText("Correo");

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lstGrado.setEnabled(false);
        jScrollPane6.setViewportView(lstGrado);

        jLabel23.setText("Turno");

        lstTelefono.setEnabled(false);
        jScrollPane8.setViewportView(lstTelefono);

        jLabel25.setText("Telefono");

        lstSexo.setEnabled(false);
        jScrollPane4.setViewportView(lstSexo);

        jLabel16.setText("Puesto laboral");

        lstEspecialidad.setEnabled(false);
        jScrollPane7.setViewportView(lstEspecialidad);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel16)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel9)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel8)
                        .addGap(51, 51, 51))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)))
                .addComponent(btnLimpiar)
                .addGap(79, 79, 79))
        );

        RegistroDeClientes.addTab("LISTA DE EMPLEADO", jPanel2);

        jLabel10.setText("Total  De Sexo Masculino:");

        jLabel11.setText("Total De Sexo Femenino:");

        jLabel12.setText("Total de Casados:");

        jLabel13.setText("Total de Solteros:");

        jLabel14.setText("Total de Viudos:");

        jLabel15.setText("Total de Divorciados:");

        txtTotalMas.setEditable(false);

        txtTotalFem.setEditable(false);

        txtTotalCas.setEditable(false);

        txtTotalSolt.setEditable(false);

        txtTotalViu.setEditable(false);

        txtTotalDiv.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalSolt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalViu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalDiv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalMas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalFem)
                    .addComponent(txtTotalCas))
                .addGap(314, 314, 314))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTotalMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTotalFem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTotalCas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtTotalSolt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotalViu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTotalDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        RegistroDeClientes.addTab("ESTADISTICA DE DOCENTES", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegistroDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(RegistroDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        CodigoEmpleado.removeAllElements();
        NombreEmpleado.removeAllElements();
        CorreoEmpleado.removeAllElements();
        SexoEmpleado.removeAllElements();
        SeccionEmpleado.removeAllElements();
        GradoEmpleado.removeAllElements();
        TelefonoEmpleado.removeAllElements();
        EspecialidadEmpleado.removeAllElements();

        // Luego, actualiza los modelos de las listas
        this.lstCodigo.setModel(CodigoEmpleado);
        this.lstNombre.setModel(NombreEmpleado);
        this.lstCorreo.setModel(CorreoEmpleado);
        this.lstSexo.setModel(SexoEmpleado);
        this.lstGrado.setModel(GradoEmpleado);
        this.lstSeccion.setModel(SeccionEmpleado);
        this.lstTelefono.setModel(TelefonoEmpleado);
        this.lstEspecialidad.setModel(EspecialidadEmpleado);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String telefonotext = txtTelefono.getText();
        String direccion = txtDireccion.getText();
        String DNI = txtDNI.getText();
        String apellido = txtApellido.getText();
        String correo = txtCorreo.getText();
        String sexo = "";
        int grado = cbGrado.getSelectedIndex();
        int estado = cbEstado.getSelectedIndex();
        String gradotext = "";
        int seccion = cbSeccion.getSelectedIndex();
        int curso = cbEspecialidad.getSelectedIndex();
        String ref = "";

        boolean generar = false;
        if (!validarCamposVacios()&&!GradoCursoSeccion()) {
            return;
        }

        switch (estado) {
            case 0:
            ref = null;
            JOptionPane.showMessageDialog(this, "Seleccione un grado.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);
            break;
            case 1:
            ref = "Soltero(a)";
            break;
            case 2:
            ref = "Casado(a)";
            break;
            case 3:
            ref = "Divorciado(a)";
            break;
            case 4:
            ref = "Viudo(a)";
            break;
            default:
            JOptionPane.showMessageDialog(this, "Seleccione un grado.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }

        switch (curso) {
            case 0:
            gradotext = null;
            JOptionPane.showMessageDialog(this, "Seleccione un curso.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);
            break;
            case 1:
            gradotext = "ALG";
            break;
            case 2:
            gradotext = "AMT";
            break;
            case 3:
            gradotext = "BIO";
            break;
            case 4:
            gradotext = "CIV";
            break;
            case 5:
            gradotext = "CMP";
            break;
            case 6:
            gradotext = "ECO";
            break;
            case 7:
            gradotext = "EDF";
            break;
            case 8:
            gradotext = "FSC";
            break;
            case 9:
            gradotext = "GOF";
            break;
            case 10:
            gradotext = "GEM";
            break;
            case 11:
            gradotext = "HST";
            break;
            case 12:
            gradotext = "ING";
            break;
            case 13:
            gradotext = "LEG";
            break;
            case 14:
            gradotext = "TRI";
            break;
            case 15:
            gradotext = "QMC";
            break;
            default:
            JOptionPane.showMessageDialog(this, "Seleccione un curso.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);
            break;
        }

        // Extracting the selected gender
        if (rbMasculino.isSelected()) {
            sexo = "Masculino";
        } else if (rbFemenino.isSelected()) {
            sexo = "Femenino";
        }

        if (nombre.isEmpty() || telefonotext.isEmpty() || direccion.isEmpty() || sexo.isEmpty()|| gradotext.isEmpty() || ref.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Error: Por favor llenar todos los datos y su sexo.",
                "Error de entrada", JOptionPane.ERROR_MESSAGE);
            generar = true;
        } else {
            String generatedCode = "";
            if (nombre.length() >= 2) {
                generatedCode += nombre.substring(0, 2);
            } else {
                generatedCode += String.format("%-2s", nombre).replace(' ', '0');
            }

            if (telefonotext.length() >= 1) {
                generatedCode += telefonotext.substring(telefonotext.length() - 1);
            } else {
                generatedCode += String.format("%-1s", telefonotext).replace(' ', '0');
            }

            if (ref.length() >= 3) {
                generatedCode += ref.substring(0, 3);
            } else {
                generatedCode += String.format("%-3s", ref).replace(' ', '0');
            }

            if (sexo.length() >= 2) {
                generatedCode += sexo.substring(0, 2);
            } else {
                generatedCode += String.format("%-2s", sexo).replace(' ', '0');
            }

            if (gradotext.length() >= 3) {
                generatedCode += gradotext.substring(0, 3);
            } else {
                generatedCode += String.format("%-3s", gradotext).replace(' ', '0');
            }

            try {
                int telefono = Integer.parseInt(telefonotext);
            } catch (NumberFormatException e) {
                // Mensaje de error en caso de que el usuario ingrese un valor no numérico
                JOptionPane.showMessageDialog(this, "Solo se permiten números en el campo de TELEFONO.",
                    "Error de entrada", JOptionPane.ERROR_MESSAGE);
                return; // Detiene la ejecución del método si el usuario ingresa un valor no numérico
            }
            try {
                int DNIS = Integer.parseInt(DNI);
            } catch (NumberFormatException e) {
                // Mensaje de error en caso de que el usuario ingrese un valor no numérico
                JOptionPane.showMessageDialog(this, "Solo se permiten números en el campo de DNI.",
                    "Error de entrada", JOptionPane.ERROR_MESSAGE);
                return; // Detiene la ejecución del método si el usuario ingresa un valor no numérico
            }
            txtCodigo.setText(generatedCode);
        }
    }//GEN-LAST:event_btnCodigoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        String nuevoNombreApellido = this.txtApellido.getText() + " " + this.txtNombre.getText();
        if (!listaEmpleado.contains(nuevoNombreApellido)){
            listaEmpleado.addElement(nuevoNombreApellido);
        }else{
            JOptionPane.showMessageDialog(null, "Error: Nombre y apellido repetidos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sexo = null;
        String estado = null;
        String seccion = null;
        int gra = 0;
        String grado = null;
        String gaaa = null;
        String telefono = null;
        String especialidad = null;

        if (rbFemenino.isSelected()) {
            sexo = "Femenino";
        } else if (rbMasculino.isSelected()) {
            sexo = "Masculino";
        }

        switch(gra){
            case 0 -> grado = null;
            case 1 -> grado = "1er Grado";
            case 2 -> grado = "2do Grado";
            case 3 -> grado = "3er Grado";
            case 4 -> grado = "4to Grado";
            case 5 -> grado = "5to Grado";
        }

        seccion = (String) cbSeccion.getSelectedItem();
        gaaa = (String) cbGrado.getSelectedItem();
        telefono = (String)(txtTelefono.getText());
        especialidad = (String)(cbEspecialidad.getSelectedItem());

        CodigoEmpleado.addElement(this.txtCodigo.getText());
        NombreEmpleado.addElement(this.txtNombre.getText());
        /**Correo.addElement(this.cbSeccion.getSelectedItem());*/
        CorreoEmpleado.addElement(this.txtCorreo.getText());
        SexoEmpleado.addElement(sexo);
        SeccionEmpleado.addElement(seccion);
        GradoEmpleado.addElement(gaaa);
        TelefonoEmpleado.addElement(telefono);
        EspecialidadEmpleado.addElement(especialidad);

        this.lstCodigo.setModel(CodigoEmpleado);
        this.lstNombre.setModel(NombreEmpleado);
        this.lstCorreo.setModel(CorreoEmpleado);
        this.lstSexo.setModel(SexoEmpleado);
        this.lstSeccion.setModel(SeccionEmpleado);
        this.lstGrado.setModel(GradoEmpleado);
        this.lstTelefono.setModel(TelefonoEmpleado);
        this.lstEspecialidad.setModel(EspecialidadEmpleado);

        totalMasculinoEmpleado++;
        totalFemeninoEmpleado++;
        totalCasadoEmpleado++;
        totalSolterosEmpleado++;
        totalViudosEmpleado++;
        totalDivorciadosEmpleado++;

        // Actualizar el campo de texto con el total
        this.txtTotalMas.setText(Integer.toString(totalMasculinoEmpleado));
        this.txtTotalFem.setText(Integer.toString(totalFemeninoEmpleado));
        this.txtTotalCas.setText(Integer.toString(totalCasadoEmpleado));
        this.txtTotalSolt.setText(Integer.toString(totalSolterosEmpleado));
        this.txtTotalViu.setText(Integer.toString(totalViudosEmpleado));
        this.txtTotalDiv.setText(Integer.toString(totalDivorciadosEmpleado));
        /**this.lstSexo.setModel(codigo);
        this.lstEstado.setModel(nivel1);**/
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        cbSeccion.addItem("elegir Seccion...");
        cbSeccion.addItem("ONP");
        cbSeccion.addItem("AFP");
        cbSeccion.addItem("ESSALUD");
        cbGrado.addItem("Elegir Grado...");
        cbGrado.addItem("MAÑANA");
        cbGrado.addItem("TARDE");

        cbEspecialidad.addItem("Puesto...");
        cbEspecialidad.addItem("Psicologo");
        cbEspecialidad.addItem("Personal de Limpieza");
        cbEspecialidad.addItem("Enfermero");
        cbEspecialidad.addItem("Director");        
        cbEspecialidad.addItem("Personal administrativo");
        cbEspecialidad.addItem("Tutoria");

        cbEstado.addItem("Elegir...ESTADO");
        cbEstado.addItem("Soltero(a)");
        cbEstado.addItem("Casado(a)");
        cbEstado.addItem("Divorciado(a)");
        cbEstado.addItem("Viudo(a)");
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyReleased
        // TODO add your handling code here:
        String texto = txtDNI.getText();
    
    // Limpiar el campo de cualquier caracter no numérico
    StringBuilder sb = new StringBuilder();
    for (char c : texto.toCharArray()) {
        if (Character.isDigit(c)) {
            sb.append(c);
        } else {
            // Mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, ingrese solo números.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Establecer el texto limpio en el campo
    txtDNI.setText(sb.toString());
    
    // Llamar a la función de verificación de campos
    }//GEN-LAST:event_txtDNIKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        String texto = txtTelefono.getText();
    
    // Limpiar el campo de cualquier caracter no numérico
    StringBuilder sb = new StringBuilder();
    for (char c : texto.toCharArray()) {
        if (Character.isDigit(c)) {
            sb.append(c);
        } else {
            // Mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, ingrese solo números.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Establecer el texto limpio en el campo
    txtTelefono.setText(sb.toString());
    
    // Llamar a la función de verificación de campos
    
    }//GEN-LAST:event_txtTelefonoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane RegistroDeClientes;
    private javax.swing.JButton btnCodigo;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbGrado;
    private javax.swing.JComboBox<String> cbSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<String> lstCodigo;
    private javax.swing.JList<String> lstCorreo;
    private javax.swing.JList<String> lstEspecialidad;
    private javax.swing.JList<String> lstGrado;
    private javax.swing.JList<String> lstNombre;
    private javax.swing.JList<String> lstSeccion;
    private javax.swing.JList<String> lstSexo;
    private javax.swing.JList<String> lstTelefono;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JPanel sds;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotalCas;
    private javax.swing.JTextField txtTotalDiv;
    private javax.swing.JTextField txtTotalFem;
    private javax.swing.JTextField txtTotalMas;
    private javax.swing.JTextField txtTotalSolt;
    private javax.swing.JTextField txtTotalViu;
    // End of variables declaration//GEN-END:variables
}
