/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.aea;

import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Morales
 */
public class RegistroNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroNotas
     */
    
    public RegistroNotas() {
        
        initComponents();
       
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private JButton lastButtonPressed = null;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtCodigoDocente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDNIDocente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnLimpiar2 = new javax.swing.JButton();
        btnBuscar2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtExamenes1 = new javax.swing.JTextField();
        txtPracticas1 = new javax.swing.JTextField();
        txtCuadernos1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtExamenes2 = new javax.swing.JTextField();
        txtPracticas2 = new javax.swing.JTextField();
        txtCuadernos2 = new javax.swing.JTextField();
        txtExamenes3 = new javax.swing.JTextField();
        txtPracticas3 = new javax.swing.JTextField();
        txtCuadernos3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPromedios1 = new javax.swing.JTextField();
        txtPromedios2 = new javax.swing.JTextField();
        txtPromedios3 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtExamenes4 = new javax.swing.JTextField();
        txtPracticas4 = new javax.swing.JTextField();
        txtCuadernos4 = new javax.swing.JTextField();
        txtPromedios4 = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtDNIAlumno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbGrado = new javax.swing.JComboBox<>();
        cbSeccion = new javax.swing.JComboBox<>();
        txtNombres = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Docente"));
        jPanel3.setPreferredSize(new java.awt.Dimension(240, 240));

        txtCodigoDocente.setPreferredSize(new java.awt.Dimension(100, 22));
        txtCodigoDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDocenteActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo del Docente");

        txtDNIDocente.setMinimumSize(new java.awt.Dimension(100, 20));
        txtDNIDocente.setPreferredSize(new java.awt.Dimension(100, 22));
        txtDNIDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIDocenteActionPerformed(evt);
            }
        });

        jLabel9.setText("DNI del Docente");

        btnLimpiar2.setText("Limpiar");
        btnLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar2ActionPerformed(evt);
            }
        });

        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Curso del Docente");

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el curso", "Matematicas", "Lenguaje", "Historia", "Ciencias" }));
        cbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDNIDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigoDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCurso, 0, 150, Short.MAX_VALUE))
                .addGap(11, 11, 11))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnBuscar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar2)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNIDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar2)
                    .addComponent(btnLimpiar2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Notas"));
        jPanel2.setPreferredSize(new java.awt.Dimension(346, 400));

        jLabel12.setText("Examenes");

        jLabel13.setText("Practicas");

        jLabel14.setText("Cuadernos");

        txtExamenes1.setPreferredSize(new java.awt.Dimension(50, 22));
        txtExamenes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExamenes1ActionPerformed(evt);
            }
        });

        txtPracticas1.setPreferredSize(new java.awt.Dimension(50, 22));
        txtPracticas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPracticas1ActionPerformed(evt);
            }
        });

        txtCuadernos1.setPreferredSize(new java.awt.Dimension(50, 22));
        txtCuadernos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuadernos1ActionPerformed(evt);
            }
        });

        jLabel11.setText("1er Ciclo");

        jLabel15.setText("2do Ciclo");

        jLabel16.setText("3er Ciclo");

        jLabel17.setText("4to Ciclo");

        txtExamenes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExamenes2ActionPerformed(evt);
            }
        });

        txtPracticas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPracticas2ActionPerformed(evt);
            }
        });

        txtCuadernos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuadernos2ActionPerformed(evt);
            }
        });

        txtExamenes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExamenes3ActionPerformed(evt);
            }
        });

        txtPracticas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPracticas3ActionPerformed(evt);
            }
        });

        txtCuadernos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuadernos3ActionPerformed(evt);
            }
        });

        jLabel18.setText("Promedios");

        txtPromedios1.setEnabled(false);
        txtPromedios1.setPreferredSize(new java.awt.Dimension(50, 22));
        txtPromedios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromedios1ActionPerformed(evt);
            }
        });

        txtPromedios2.setEnabled(false);
        txtPromedios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromedios2ActionPerformed(evt);
            }
        });

        txtPromedios3.setEnabled(false);
        txtPromedios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromedios3ActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular Promedios");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Datos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtPromedios4.setEnabled(false);

        txtObservacion.setEnabled(false);

        jLabel20.setText("Observacion");

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPracticas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtExamenes1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCuadernos1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtPromedios1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtExamenes2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtPracticas2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtCuadernos2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtPromedios2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPracticas3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtExamenes3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPromedios3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCuadernos3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalir))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtExamenes4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtPracticas4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtCuadernos4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtPromedios4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jLabel20)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtObservacion)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(65, 65, 65))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtExamenes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExamenes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExamenes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExamenes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPracticas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPracticas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPracticas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPracticas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCuadernos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuadernos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuadernos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuadernos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPromedios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPromedios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPromedios3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPromedios4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObservacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("Registro de Notas por Alumno");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("¿Que desea hacer hoy, Docente?");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        btnActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnActualizarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Alumno"));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 240));

        jLabel3.setText("Apellidos");

        jLabel4.setText("Correo del Alumno");

        txtApellidos.setPreferredSize(new java.awt.Dimension(100, 22));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        txtDNIAlumno.setMinimumSize(new java.awt.Dimension(100, 20));
        txtDNIAlumno.setPreferredSize(new java.awt.Dimension(100, 22));
        txtDNIAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIAlumnoActionPerformed(evt);
            }
        });

        jLabel8.setText("DNI del Alumno");

        jLabel2.setText("Grado");

        jLabel5.setText("Seccion");

        cbGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el grado", "1º Grado", "2º Grado", "3º Grado", "4º Grado", "5º Grado" }));
        cbGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGradoActionPerformed(evt);
            }
        });

        cbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la seccion", "A", "B", "C" }));
        cbSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeccionActionPerformed(evt);
            }
        });

        txtNombres.setPreferredSize(new java.awt.Dimension(100, 22));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombres");

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        txtCorreo.setMinimumSize(new java.awt.Dimension(100, 20));
        txtCorreo.setPreferredSize(new java.awt.Dimension(100, 22));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSeccion, 0, 165, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnBuscar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar1)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDNIAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNIAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar1)
                    .addComponent(btnBuscar1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDocenteActionPerformed

    private void txtDNIDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIDocenteActionPerformed

    private void btnLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar2ActionPerformed
        // TODO add your handling code here:
        String name= null;
    }//GEN-LAST:event_btnLimpiar2ActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        // TODO add your handling code here:
        String DNI = txtDNIDocente.getText();
        String codigo = txtCodigoDocente.getText();
        int selectedIndex = cbCurso.getSelectedIndex();

        if (DNI.isEmpty() || codigo.isEmpty() || selectedIndex == 0 ) {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes");
        } else {
            JOptionPane.showMessageDialog(null, "Docente encontrado, bienvenido!");
        }
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void cbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCursoActionPerformed

    private void txtExamenes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamenes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamenes1ActionPerformed

    private void txtPracticas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPracticas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPracticas1ActionPerformed

    private void txtCuadernos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuadernos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuadernos1ActionPerformed

    private void txtExamenes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamenes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamenes2ActionPerformed

    private void txtPracticas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPracticas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPracticas2ActionPerformed

    private void txtCuadernos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuadernos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuadernos2ActionPerformed

    private void txtExamenes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamenes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamenes3ActionPerformed

    private void txtPracticas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPracticas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPracticas3ActionPerformed

    private void txtCuadernos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuadernos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuadernos3ActionPerformed

    private void txtPromedios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromedios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromedios1ActionPerformed

    private void txtPromedios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromedios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromedios2ActionPerformed

    private void txtPromedios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromedios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromedios3ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String dni = txtDNIAlumno.getText();
        String correo = txtCorreo.getText();
        String grado = (String) cbGrado.getSelectedItem();
        String seccion = (String) cbSeccion.getSelectedItem();

        if (nombres.isEmpty() || apellidos.isEmpty() || dni.isEmpty() || correo.isEmpty() || grado == null || seccion == null) {
            JOptionPane.showMessageDialog(null, "Por favor, antes de hacer algun cambio asegurese de tener los datos de Alumno/Docente correctos");
        } else {
            int examen1 = Integer.parseInt(txtExamenes1.getText());
            int practicas1 = Integer.parseInt(txtPracticas1.getText());
            int cuadernos1 = Integer.parseInt(txtCuadernos1.getText());

            int promedio1 = (examen1 + practicas1 + cuadernos1) / 3;
            txtPromedios1.setText(Integer.toString(promedio1));

            int examen2 = Integer.parseInt(txtExamenes2.getText());
            int practicas2 = Integer.parseInt(txtPracticas2.getText());
            int cuadernos2 = Integer.parseInt(txtCuadernos2.getText());

            int promedio2 = (examen2 + practicas2 + cuadernos2) / 3;
            txtPromedios2.setText(Integer.toString(promedio2));

            int examen3 = Integer.parseInt(txtExamenes3.getText());
            int practicas3 = Integer.parseInt(txtPracticas3.getText());
            int cuadernos3 = Integer.parseInt(txtCuadernos3.getText());

            int promedio3 = (examen3 + practicas3 + cuadernos3) / 3;
            txtPromedios3.setText(Integer.toString(promedio3));

            int examen4 = Integer.parseInt(txtExamenes4.getText());
            int practicas4 = Integer.parseInt(txtPracticas4.getText());
            int cuadernos4 = Integer.parseInt(txtCuadernos4.getText());

            int promedio4 = (examen4 + practicas4 + cuadernos4) / 3;
            txtPromedios4.setText(Integer.toString(promedio4));

            int nota1 = Integer.parseInt(txtPromedios1.getText());
            int nota2 = Integer.parseInt(txtPromedios2.getText());
            int nota3 = Integer.parseInt(txtPromedios3.getText());
            int nota4 = Integer.parseInt(txtPromedios4.getText());

            if (nota1 > 13 && nota2 > 13 && nota3 > 13 && nota4 > 13) {
                // Si todas las notas son mayores que 13, muestra "Alumno aprobado!"
                txtObservacion.setText("Alumno aprobado!");
            } else {
                // Si alguna nota es menor o igual a 13, muestra "Alumno desaprobado"
                txtObservacion.setText("Alumno desaprobado");
            }

        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        if (lastButtonPressed == btnRegistrar) {
            txtExamenes1.setText("");
            txtExamenes2.setText("");
            txtExamenes3.setText("");
            txtExamenes4.setText("");
            txtPracticas1.setText("");
            txtPracticas2.setText("");
            txtPracticas3.setText("");
            txtPracticas4.setText("");
            txtCuadernos1.setText("");
            txtCuadernos2.setText("");
            txtCuadernos3.setText("");
            txtCuadernos4.setText("");
            txtPromedios1.setText("");
            txtPromedios2.setText("");
            txtPromedios3.setText("");
            txtPromedios4.setText("");
        } else if (lastButtonPressed == btnActualizar) {
            txtExamenes4.setText("");
            txtPracticas4.setText("");
            txtCuadernos4.setText("");
            txtPromedios4.setText("");
        }
        txtObservacion.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de salir?",
            "Confirmar salir",
            JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        lastButtonPressed = btnRegistrar;
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String dni = txtDNIAlumno.getText();
        String correo = txtCorreo.getText();
        String grado = (String) cbGrado.getSelectedItem();
        String seccion = (String) cbSeccion.getSelectedItem();

        if (nombres.isEmpty() || apellidos.isEmpty() || dni.isEmpty() || correo.isEmpty() || grado == null || seccion == null) {
            JOptionPane.showMessageDialog(null, "Por favor, antes de hacer algun cambio asegurese de tener los datos de Alumno/Docente correctos");
        } else {
            Random rand = new Random();
            int min = 13, max = 20;
            txtExamenes1.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtExamenes2.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtExamenes3.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtPracticas1.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtPracticas2.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtPracticas3.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtCuadernos1.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtCuadernos2.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtCuadernos3.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        lastButtonPressed = btnActualizar;
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String dni = txtDNIAlumno.getText();
        String correo = txtCorreo.getText();
        String grado = (String) cbGrado.getSelectedItem();
        String seccion = (String) cbSeccion.getSelectedItem();

        if (nombres.isEmpty() || apellidos.isEmpty() || dni.isEmpty() || correo.isEmpty() || grado == null || seccion == null) {
            JOptionPane.showMessageDialog(null, "Por favor, antes de hacer algun cambio asegurese de tener los datos de Alumno/Docente correctos");
        } else {
            Random rand = new Random();
            int min = 13, max = 20;
            txtExamenes1.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtExamenes2.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtExamenes3.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtPracticas1.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtPracticas2.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtPracticas3.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtCuadernos1.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtCuadernos2.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
            txtCuadernos3.setText(Integer.toString(rand.nextInt(max - min + 1) + min));
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtDNIAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIAlumnoActionPerformed

    private void cbGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGradoActionPerformed

    private void cbSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeccionActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String dni = txtDNIAlumno.getText();
        String correo = txtCorreo.getText();
        String grado = (String) cbGrado.getSelectedItem();
        String seccion = (String) cbSeccion.getSelectedItem();
        int selectedIndex1 = cbGrado.getSelectedIndex();
        int selectedIndex2 = cbSeccion.getSelectedIndex();

        if (nombres.isEmpty() || apellidos.isEmpty() || dni.isEmpty() || correo.isEmpty() || grado == null || seccion == null || selectedIndex1 == 0 || selectedIndex2 == 0) {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes");
        } else {
            JOptionPane.showMessageDialog(null, "Alumno " + nombres + " " + apellidos + " fue encontrado!");
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDNIAlumno.setText("");
        txtCorreo.setText("");
        cbGrado.setSelectedIndex(0);
        cbSeccion.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnActualizarKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnActualizarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnLimpiar2;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbGrado;
    private javax.swing.JComboBox<String> cbSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigoDocente;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCuadernos1;
    private javax.swing.JTextField txtCuadernos2;
    private javax.swing.JTextField txtCuadernos3;
    private javax.swing.JTextField txtCuadernos4;
    private javax.swing.JTextField txtDNIAlumno;
    private javax.swing.JTextField txtDNIDocente;
    private javax.swing.JTextField txtExamenes1;
    private javax.swing.JTextField txtExamenes2;
    private javax.swing.JTextField txtExamenes3;
    private javax.swing.JTextField txtExamenes4;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPracticas1;
    private javax.swing.JTextField txtPracticas2;
    private javax.swing.JTextField txtPracticas3;
    private javax.swing.JTextField txtPracticas4;
    private javax.swing.JTextField txtPromedios1;
    private javax.swing.JTextField txtPromedios2;
    private javax.swing.JTextField txtPromedios3;
    private javax.swing.JTextField txtPromedios4;
    // End of variables declaration//GEN-END:variables
}
